### PR TITLE
Feat tweaks

### PR DESCRIPTION
**Pull request by daniagudelos**
New features:

- Display a notification when a topology has been saved
- Display a dialog asking if the topology should be saved when there are unsaved changes
- Add the possibility to select visualize and refresh CO2 profiles on the GUI side. Note: This change is not yet connected with memapCore.

Fix:
- Positions are now stored by each building icon. Serialization and deserialization are correct.
- Connections are updated when the building name or position changes

### CODE REVIEW

**Comment by bytschkow** [comment]
Let's make the pull request from Jan first.

**Review by bytschkow — CHANGES_REQUESTED** [review]
I get the following errors:

When loading existing example.
- [x]  'Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at fortiss.serialization.ParametersTypeAdapter.deserialize(ParametersTypeAdapter.java:51)
	at fortiss.serialization.ParametersTypeAdapter.deserialize(ParametersTypeAdapter.java:1)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)...'

Starting without last file --> works well. Further comments:
- [ ]  (optional, since this is rather a feature request) when the simulation 7 days one chart is not well readable: see also testing
- [ ]  reading demand from empty resources: 
`>> Reading from resources: CONSUMPTIONEXAMPLE0
Error reading 
Reading new format of 
>> Reading from source: 
java.io.FileNotFoundException:  (Result too large)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)`

- [ ]  Can the saved notification be only appearing for a second? Without the neet to click on 'ok'?
- [ ]  Confilct, which is easy to resolve.

**Comment by daniagudelos** [comment]
> * [ ]   'Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
>   at fortiss.serialization.ParametersTypeAdapter.deserialize(ParametersTypeAdapter.java:51)
>   at fortiss.serialization.ParametersTypeAdapter.deserialize(ParametersTypeAdapter.java:1)
>   at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)...'

_The file you are using probably corresponds to a previous version of MEMAP. The line where the error appears indicates that the file does not have a node called "co2Emissions". This is a new parameter, therefore it is not included in previous versions of the tool. Could you please confirm?_

> Starting without last file --> works well. Further comments:
> 
> * [ ]   (optional, since this is rather a feature request) when the simulation 7 days one chart is not well readable: see also testing

_I created an issue to address the request:  #170_

> * [ ]   reading demand from empty resources:
>   `>> Reading from resources: CONSUMPTIONEXAMPLE0
>   Error reading
>   Reading new format of
> > > Reading from source:
> > > java.io.FileNotFoundException:  (Result too large)
> > > at java.io.FileInputStream.open0(Native Method)
> > > at java.io.FileInputStream.open(Unknown Source)
> > > at java.io.FileInputStream.(Unknown Source)
> > > at java.io.FileInputStream.(Unknown Source)`

_Could you please provide a longer description of the problem? I tried to reproduce by using CONSUMPTIONEXAMPLE0 in one demand component. The program did not throw an error and the simulation completed successfully. _ 

image

> * [ ]   Can the saved notification be only appearing for a second? Without the neet to click on 'ok'?
_I created an issue to address the request #171_

> * [ ]   Confilct, which is easy to resolve.

_Yes. I already rebased this branch to the development branch._

**Comment by daniagudelos** [comment]
Issue #170 is closed in 0261f70e587dd53bbaa35f6bf044e2a020000786
Issue #171 is closed in 6c0a190017627914528c4e8ce03760f885e3e1cf
The error reported when reading from resurces is fixed in f612b676a65c6245b1b9f95ebddae4cfc28d53be

**Review by bytschkow — APPROVED** [review]
Passt :-)

**Pull request merged**
